# Generated by Django 3.1.5 on 2021-01-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='notes',
        ),
    ]
