# Generated by Django 3.1.5 on 2021-02-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210202_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='items',
            field=models.ManyToManyField(to='main_app.Item'),
        ),
    ]
