# Generated by Django 3.1.5 on 2021-02-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210202_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='trips',
            field=models.ManyToManyField(to='main_app.Trip'),
        ),
    ]
